# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bionode_common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'bionode_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ionode_common.proto\x12\x11\x62ionode.common.v1\"\x07\n\x05\x45mpty\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x19\n\nIdsRequest\x12\x0b\n\x03ids\x18\x01 \x03(\t\"Q\n\x0bPageRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x0f\n\x07keyword\x18\x03 \x01(\t\x12\x10\n\x08order_by\x18\x04 \x01(\t\"S\n\x0cPageResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\x12\x13\n\x0btotal_pages\x18\x04 \x01(\x05\"D\n\x08Metadata\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x13\n\x0b\x63reate_time\x18\x02 \x01(\t\x12\x13\n\x0bupdate_time\x18\x03 \x01(\t\",\n\x11OperationResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"[\n\nOptionItem\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12/\n\x08\x63hildren\x18\x03 \x03(\x0b\x32\x1d.bionode.common.v1.OptionItem\"<\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x65tails_json\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bionode_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=43
  _globals['_EMPTY']._serialized_end=50
  _globals['_IDREQUEST']._serialized_start=52
  _globals['_IDREQUEST']._serialized_end=75
  _globals['_IDSREQUEST']._serialized_start=77
  _globals['_IDSREQUEST']._serialized_end=102
  _globals['_PAGEREQUEST']._serialized_start=104
  _globals['_PAGEREQUEST']._serialized_end=185
  _globals['_PAGERESPONSE']._serialized_start=187
  _globals['_PAGERESPONSE']._serialized_end=270
  _globals['_METADATA']._serialized_start=272
  _globals['_METADATA']._serialized_end=340
  _globals['_OPERATIONRESPONSE']._serialized_start=342
  _globals['_OPERATIONRESPONSE']._serialized_end=386
  _globals['_OPTIONITEM']._serialized_start=388
  _globals['_OPTIONITEM']._serialized_end=479
  _globals['_ERROR']._serialized_start=481
  _globals['_ERROR']._serialized_end=541
# @@protoc_insertion_point(module_scope)
