# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import uburnode_pb2 as uburnode__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in uburnode_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAudio = channel.unary_unary(
                '/uburnode.v1.AudioService/CreateAudio',
                request_serializer=uburnode__pb2.CreateAudioReq.SerializeToString,
                response_deserializer=uburnode__pb2.AudioMaterialRes.FromString,
                _registered_method=True)
        self.UpdateAudio = channel.unary_unary(
                '/uburnode.v1.AudioService/UpdateAudio',
                request_serializer=uburnode__pb2.UpdateAudioReq.SerializeToString,
                response_deserializer=uburnode__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.DeleteAudio = channel.unary_unary(
                '/uburnode.v1.AudioService/DeleteAudio',
                request_serializer=uburnode__pb2.IdRequest.SerializeToString,
                response_deserializer=uburnode__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.SearchAudio = channel.unary_unary(
                '/uburnode.v1.AudioService/SearchAudio',
                request_serializer=uburnode__pb2.SearchAudioReq.SerializeToString,
                response_deserializer=uburnode__pb2.SearchAudioRes.FromString,
                _registered_method=True)


class AudioServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAudio,
                    request_deserializer=uburnode__pb2.CreateAudioReq.FromString,
                    response_serializer=uburnode__pb2.AudioMaterialRes.SerializeToString,
            ),
            'UpdateAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAudio,
                    request_deserializer=uburnode__pb2.UpdateAudioReq.FromString,
                    response_serializer=uburnode__pb2.OperationResponse.SerializeToString,
            ),
            'DeleteAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAudio,
                    request_deserializer=uburnode__pb2.IdRequest.FromString,
                    response_serializer=uburnode__pb2.OperationResponse.SerializeToString,
            ),
            'SearchAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchAudio,
                    request_deserializer=uburnode__pb2.SearchAudioReq.FromString,
                    response_serializer=uburnode__pb2.SearchAudioRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uburnode.v1.AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uburnode.v1.AudioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uburnode.v1.AudioService/CreateAudio',
            uburnode__pb2.CreateAudioReq.SerializeToString,
            uburnode__pb2.AudioMaterialRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uburnode.v1.AudioService/UpdateAudio',
            uburnode__pb2.UpdateAudioReq.SerializeToString,
            uburnode__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uburnode.v1.AudioService/DeleteAudio',
            uburnode__pb2.IdRequest.SerializeToString,
            uburnode__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uburnode.v1.AudioService/SearchAudio',
            uburnode__pb2.SearchAudioReq.SerializeToString,
            uburnode__pb2.SearchAudioRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class QuizServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnswer = channel.unary_unary(
                '/uburnode.v1.QuizService/GetAnswer',
                request_serializer=uburnode__pb2.GetAnswerReq.SerializeToString,
                response_deserializer=uburnode__pb2.GetAnswerRes.FromString,
                _registered_method=True)


class QuizServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuizServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnswer,
                    request_deserializer=uburnode__pb2.GetAnswerReq.FromString,
                    response_serializer=uburnode__pb2.GetAnswerRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uburnode.v1.QuizService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uburnode.v1.QuizService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuizService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uburnode.v1.QuizService/GetAnswer',
            uburnode__pb2.GetAnswerReq.SerializeToString,
            uburnode__pb2.GetAnswerRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
