# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uburnode_somni.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'uburnode_somni.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14uburnode_somni.proto\x12\x11uburnode.somni.v1\x1a\x1cgoogle/protobuf/struct.proto\".\n\x0cGetAnswerReq\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x11\n\tanswer_id\x18\x02 \x01(\t\"\x8e\x01\n\nAnswerItem\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x12\n\ninput_type\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12%\n\x05value\x18\x05 \x01(\x0b\x32\x16.google.protobuf.Value\x12\x13\n\x0b\x65xtra_input\x18\x06 \x01(\t\">\n\x0cGetAnswerRes\x12.\n\x07\x61nswers\x18\x01 \x03(\x0b\x32\x1d.uburnode.somni.v1.AnswerItem2\\\n\x0bQuizService\x12M\n\tGetAnswer\x12\x1f.uburnode.somni.v1.GetAnswerReq\x1a\x1f.uburnode.somni.v1.GetAnswerResb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uburnode_somni_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETANSWERREQ']._serialized_start=73
  _globals['_GETANSWERREQ']._serialized_end=119
  _globals['_ANSWERITEM']._serialized_start=122
  _globals['_ANSWERITEM']._serialized_end=264
  _globals['_GETANSWERRES']._serialized_start=266
  _globals['_GETANSWERRES']._serialized_end=328
  _globals['_QUIZSERVICE']._serialized_start=330
  _globals['_QUIZSERVICE']._serialized_end=422
# @@protoc_insertion_point(module_scope)
